title:               Jeff Lembeck learns a code or two
tagline:             Serious code business!
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>
name:                Jeff Lembeck
twitter:             jefflembeck
github:              jlembeck
email:               jlembeck@gmail.com
google_analytics_id: YOUR_GA_ID
