title: Jeff Lembeck learns a code or two
url: http://jefflembeck.com
name: Jeff Lembeck
tagline: Serious code business!
twitter: jefflembeck
github: http://github.com/jlembeck
email: jlembeck@gmail.com
login: jlembeck
password: ch0c01473
